events {}

http {
    server {
        listen 80;
        server_name ec2-15-207-254-47.ap-south-1.compute.amazonaws.com;

        # Health check (since no frontend)
        location / {
            return 200 "Backend is running\n";
        }

        # WebSocket
        location /exotel-media {
            proxy_pass http://app:3000;
            proxy_http_version 1.1;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }

        # API
        location /api/ {
            proxy_pass http://app:3000;
        }
    }
}
